server:
  port: 9999
spring:
  application:
    name: authorization_service
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    converters:
      preferred-json-mapper: gson