spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://120.55.161.138:3306/cold_chain_logistics_sys
  cloud:
    sentinel:
      transport:
        dashboard: 120.55.161.138:8858
      eager: true
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 120.55.161.138
                port: 5672
                username: admin
                password: admin
                virtual-host: /
      bindings:
        email-out-0:
          binder: rabbit
          destination: email-destination
          content-type: application/json
    nacos:
      discovery:
        server-addr: 120.55.161.138:8848
      config:
        server-addr: 120.55.161.138:8848
        file-extension: yaml