version: '3.8'
services:
  gateway:
    container_name: gateway
    build:
      context: ./sys-gateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - mynetwork
  authorization-service:
    container_name: authorization-service
    build:
      context: ./sys-authorization
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    networks:
      - mynetwork
  hardware-service:
    container_name: hardware-service
    build:
      context: ./hardware-center
      dockerfile: Dockerfile
    ports:
      - "7999:7999"
    networks:
      - mynetwork
  message-service:
    container_name: message-service
    build:
      context: ./message-center
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
  user-service:
    container_name: user-service
    build:
      context: ./user-center
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - mynetwork
  log-service:
    container_name: log-service
    build:
      context: ./log-center
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - mynetwork
  logistics-service:
    container_name: logistic-service
    build:
      context: ./logistics-center
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - mynetwork
  order-service:
    container_name: order-service
    build:
      context: ./order-center
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    networks:
      - mynetwork
networks:
  mynetwork: