spring:
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      config:
        server-addr: 120.55.161.138:8848
        file-extension: yaml
      discovery:
        server-addr: 120.55.161.138:8848
    sentinel:
      eager: true
      transport:
        dashboard: 120.55.161.138:8858
